apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: notes-k8s-app
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: cm9vdDEyMw== #root123
  MYSQL_DATABASE: bm90ZXNkYg== #notesdb
  MYSQL_USER: bm90ZXN1c2Vy #notesuser
  MYSQL_PASSWORD: bm90ZXNwYXNz #notespass

